### ISSUE TITLE
Align docker-meta with other agents

### ISSUE THREAD

**Issue by jackshirazi** [elastic/elastic-otel-java#413]
labels, and type (raw vs semver)

**Comment by trentm** [comment]
Aligning on the labels seems easy.

---

Finding alignment on the `with.tags` config used with the `docker/metadata-action` action might be more painful.
- I recall those docs being confusing.
- Changing that config  might change what tags are published, e.g. whether the publishing of pushes to main use the "edge" docker tag or something else.

**Comment by trentm** [comment]
# docker/metadata-action "with.tags" configs currently in use

Java: https://github.com/elastic/elastic-otel-java/blob/main/.github/workflows/release-step-3.yml

```yaml
      - name: Extract metadata (tags, labels)
        id: docker-meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81  # v5.5.1
        with:
          images: ${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.RELEASE_VERSION }}
            type=raw,value=latest,enable=${{ contains(env.LATEST_TAG,env.RELEASE_VERSION) }}
```

.NET: https://github.com/elastic/elastic-otel-dotnet/blob/main/.github/workflows/release.yml#L63-L78

```yaml
    - name: Extract metadata (tags, labels)
      id: docker-meta
      uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81  # v5.5.1
      with:
        images: ${{ env.DOCKER_IMAGE_NAME }}
        flavor: |
          latest=auto
        tags: |
          # "1.2.3" and "latest" Docker tags on push of git tag "v1.2.3"
          type=semver,pattern={{version}},value=${{ steps.bootstrap.outputs.agent-version }}
          # "edge" Docker tag on git push to default branch
          type=edge
```

Node.js: https://github.com/elastic/elastic-otel-node/pull/374/files#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R51-R62

```yaml
      - name: Extract metadata (tags, labels)
        id: docker-meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81  # v5.5.1
        with:
          images: ${{ env.DOCKER_IMAGE_NAME }}
          flavor: |
            latest=auto
          tags: |
            # "1.2.3" and "latest" Docker tags on push of git tag "v1.2.3"
            type=semver,pattern={{version}}
            # "edge" Docker tag on git push to default branch
            type=edge
```

Python: https://github.com/elastic/elastic-otel-python/pull/132/files#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R87-R98

```yaml
- name: Extract metadata (tags, labels)
        id: docker-meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81  # v5.5.1
        with:
          images: ${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=raw,value=latest,prefix=test-,enable={{is_default_branch}}
            type=semver,pattern={{version}}
```
